name: Waka Readme

on:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False" 
          SHOW_LOC_CHART: "False"
          SHOW_COMMIT: "False"
          SYMBOL_VERSION: 3
          SHOW_TIMEZONE: "False"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
