name: Waka Readme

on:
  schedule:
    - cron:  '*/60 * * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False" 
          SHOW_LOC_CHART: "False"
          SHOW_COMMIT: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SYMBOL_VERSION: 2
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE: "True"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
